[project]
name = "KioskForge"
version = "0.25.0"
description = "KioskForge generates Raspberry Pi kiosks on top of Ubuntu Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt==4.3.0",
    "mypy==1.17.1",
    "pefile==2023.2.7",
    "pyinstaller==6.15.0",
    "pyinstaller-versionfile==3.0.1",
    "pylint==3.3.8",
    "pyrefly==0.26.0",
]
